Ruby on Rails capstone project - Budget app
Amazinggracee/The-budget-app pull request #12
Opened 2023-09-14 16:55 UTC by Amazinggracee

2023-09-14 18:58 UTC, t-yanick requested changes
# STATUS: CHANGES REQUIRED

Hi @Amazinggracee , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Excellent video presentation within the time limit.
:heavy_check_mark: The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
:heavy_check_mark: The video contains a demo of the project, highlighting all the project features. kudos for the piece of code your are proud of making.
:heavy_check_mark: Deployment done on Render
:heavy_check_mark: Sign up and login pages present and a user can register and log in successfully
:heavy_check_mark: All pages added as per project requirements
:heavy_check_mark: Postgres used for database and devise for authentication
:heavy_check_mark: App has unit and integration tests for all the most important components of the RoR application.
:heavy_check_mark: App works as expected

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-14 18:58 UTC, t-yanick commented on app/views/balances/index.html.erb
> +<div class="add-button">
- [ ] Great job working on this capstone. As per project requirements, you are supposed to follow the `layout` in the given design. At the moment, your `add button` does not follow the given layout. See screenshots below:
- Your design
![Screen Shot 2023-09-14 at 7 44 23 PM](https://github.com/Amazinggracee/The-budget-app/assets/62849872/80506906-bc86-43ca-af17-c0318d0a375e)
- Given design
![Screen Shot 2023-09-14 at 7 46 56 PM](https://github.com/Amazinggracee/The-budget-app/assets/62849872/bb165740-c0ec-4d4a-8bcb-5f1edb8a141b)

The add button should be at the button and the length should be the width of the page

2023-09-14 21:28 UTC, Amazinggracee commented on app/views/balances/index.html.erb
> +<div class="add-button">
@t-yanick , how are you doing today? Thank you for pointing this out. I have changed the design.

2023-09-15 00:17 UTC, Olamarx approved these changes
Hi @Amazinggracee,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>
## Highlights
- Required changes fixed ✔️
- Commit messages meaningful ✔️
- Gitflow ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-15 07:15 UTC, merged